-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

--
-- Most of the keymaps from my previous config are part of LazyVim's defaults,
-- or close to it.
--
-- The which-key plugin is great -- hit <leader> to see a menu, where the
-- defaults are cleverly organized into categories with a memorable first
-- character.
--
--For now I'm going to (a) not add any key bindings and use just LazyVim
--defaults until I have a need to customize; and (b) let which-key do its thing
--rather than maintaining a cheatsheet.
--
